name: workshops
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  #- bioconda::blast
  #- bioconda::samtools
  - graphviz
  - pip:
      #- altair
      - biopython
      - pygraphviz
      - pydot
      - matplotlib
      #- nbgrader
      - networkx
      - numpy
      - pandas
      #- pysam
      - regex
      #- scikit-learn
      - scipy
      - seaborn
      #- umap-learn
      #- vega
